version: '3'

services:
  angular-services: 
    container_name: angular_container
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes:
      - "./../:/app"